name: Repository Dispatch
on:
  repository_dispatch:
    types: [repo-released]
jobs:
  Build and Push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.client_payload.repo_name }}
          ref: ${{ github.event.client_payload.ref }}
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          registry: binaryartifacts-test-github.jfrog.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}         
      - name: Push to artifactory
        uses: docker/build-push-action@v2
        with:
          tags: |
            binaryartifacts-test-github.jfrog.io/test-repo:latest
            binaryartifacts-test-github.jfrog.io/test-repo:${{ github.event.client_payload.tag_name }}
          file: Dockerfile.build
          push: true
          
          
