name: Build and Publish
on:
  repository_dispatch:
    types: [repo-released]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.client_payload.repo_name }}
          ref: ${{ github.event.client_payload.ref }}
      - name: Login to artifactory docker
        uses: docker/login-action@v1 
        with:
          registry: binaryartifacts-test-github.jfrog.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Push to artifactory docker
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.build
          push: true
          tags: |
            binaryartifacts-test-github.jfrog.io/test-repo:latest
            binaryartifacts-test-github.jfrog.io/test-repo:${{ github.event.client_payload.tag_name }}
          
          
